/* messages */
export const MESSAGE_DELIVERED = 'MESSAGE_DELIVERED';
export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const TOGGLE_TYPING = 'TOGGLE_TYPING';
export const UPDATE_TYPERS = 'UPDATE_TYPERS';
export const UPDATE_SENDBAR_HEIGHT = 'UPDATE_SENDBAR_HEIGHT';

/* websockets */
export const CONNECT_TO_SERVER = 'CONNECT_TO_SERVER';
export const UPDATE_HEAD_HEIGHT = 'UPDATE_HEAD_HEIGHT';
export const REGISTER_USER = 'REGISTER_USER';